<ShowQRCode>:
    name: 'showqrcode'
    BoxLayout:
        orientation: 'vertical'
        size_hint: (None, None)
        pos_hint:{'center_x': .5, 'top': 0.9}
        size: (app.window_size[0]/1.8, app.window_size[0]/1.8)
        id: qr
    BoxLayout:
        orientation: 'vertical'
        MyMDTextField:
            size_hint_y: None
            font_style: 'Body1'
            theme_text_color: 'Primary'
            text: app.tr._(root.address)
            multiline: True
            readonly: True
            line_color_normal: [0,0,0,0]
            _current_line_color: [0,0,0,0]
            line_color_focus: [0,0,0,0]
            halign: 'center'
            font_size: dp(15)
            bold: True
            canvas.before:
                Color:
                    rgba: (0,0,0,1)
        # MDLabel:
        #     size_hint_y: None
        #     font_style: 'Body1'
        #     theme_text_color: 'Primary'
        #     text: "[b]BM-2cV7Y8imvAevK6z6YmhYRcj2t7rghBtDSZ[/b]"
        #     markup: True
        #     pos_hint: {'x': .28, 'y': 0.6}