<Allmails>:
    name: 'allmails'
    BoxLayout:
        orientation: 'vertical'
        spacing: dp(5)
        GridLayout:
            id: identi_tag
            padding: [20, 20, 0, 5]
            spacing: dp(5)
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            MDLabel:
                id: tag_label
                text: ''
                font_style: 'Subtitle2'
        BoxLayout:
            orientation:'vertical'
            ScrollView:
                id: scroll_y
                do_scroll_x: False
                MDList:
                    id: ml
    Loader:
    ComposerButton: