#:set color_transparent (0,0,0,0) # transparent black
#:set color_black (0,0,0,1) # black

<MailDetail>:
    name: 'mailDetail'
    ScrollView:
        do_scroll_x: False
        BoxLayout:
            size_hint_y: None
            orientation: 'vertical'
            # height: dp(bod.height) + self.minimum_height
            height: self.minimum_height
            padding: dp(10)
            OneLineListTitle:
                id: subj
                text: app.tr._(root.subject)
                divider: None
                font_style: 'H5'
                theme_text_color: 'Primary'
                _no_ripple_effect: True
                long_press_time: self.long_press_time
            TwoLineAvatarIconListItem:
                id: subaft
                text: app.tr._(root.from_addr)
                secondary_text: app.tr._('to ' + root.to_addr)
                divider: None
                on_press: root.detailed_popup()
                BadgeText:
                    size_hint:(None, None)
                    size: root.badgeProperties.SIZE_ANDROID if app.app_platform == 'android' else root.badgeProperties.SIZE_OTHER
                    text: app.tr._(root.time_tag)
                    halign:'center'
                    font_style:'Caption'
                    pos_hint: {'center_y': .8}
                    _txt_right_pad: dp(70)
                    font_size: root.badgeProperties.FONT_SIZE
                MDChip:
                    size_hint: root.chipProperties.SIZE_HINT_ANDROID if app.app_platform == 'android' else root.chipProperties.SIZE_HINT_OTHER
                    text: app.tr._(root.page_type)
                    icon: ''
                    text_color: root.chipProperties.TEXT_COLOR
                    pos_hint: {'center_x': root.chipProperties.CENTER_X_ANDROID if app.app_platform == 'android' else root.chipProperties.CENTER_X_OTHER, 'center_y': root.chipProperties.CENTER_Y}
                    radius: root.chipProperties.RADIUS
                    height: self.parent.height/4
                AvatarSampleWidget:
                    source: root.avatar_image
            MDLabel:
                text: root.status
                disabled: True
                font_style: 'Body2'
                halign:'left'
                padding_x: 20
            MyMDTextField:
                id: bod
                size_hint_y: None
                font_style: 'Subtitle2'
                text: root.message
                multiline: True
                readonly: True
                line_color_normal: color_transparent
                _current_line_color: color_transparent
                line_color_focus: color_transparent
                markup: True
                font_size: '15sp'
                canvas.before:
                    Color:
                        rgba: color_black
    Loader:


<MyMDTextField@MDTextField>:
    canvas.before:
        Color:
            rgba: color_black
