#!/usr/bin/python3

import os
import pkg_resources

dist = pkg_resources.get_distribution('pybitmessage')
script_file = os.path.join(dist.location, dist.key, 'bitmessagemain.py')
new_globals = globals()
new_globals.update(__file__=script_file)

execfile(script_file, new_globals)
