#!/usr/bin/python2.7

import os
import pkg_resources


dist = pkg_resources.get_distribution('pybitmessage')
script_file = os.path.join(dist.location, dist.key, 'bitmessagemain.py')
new_globals = globals()
new_globals.update(__file__=script_file)

try:
    execfile(script_file, new_globals)
except NameError:
    exec(compile(open(script_file, "rb").read(), script_file, 'exec'), new_globals)